### PR TITLE
Create AppTweak Job offer

### PR DESCRIPTION
**Pull request by almathie**

### CODE REVIEW

**Comment by StanBoyet** [comment]
Hey @almathie !
Thanks for posting this. Before validating it, can you add it to the index of the open positions? Add an edit to this readme on your PR and we'll be good to go :) 
https://github.com/brug-be/jobboard/blob/master/README.md#open-positions

**Comment by almathie** [comment]
@StanBoyet My bad ! Just updated the PR :) Thank you very much

**Comment by almathie** [comment]
@StanBoyet Is there any more thing I need to add / change ?

**Review by StanBoyet — APPROVED** [review]

**Comment by StanBoyet** [comment]
@almathie we good :)

**Pull request merged**
