### PR TITLE
Solvace full stack ruby on rails ember

### PR DESCRIPTION
**Pull request by reinoutdeclerck**
Can be shared in all available channels

### CODE REVIEW

**Comment by joren** [comment]
👍

**Comment by joren** [comment]
thanks @reinoutdeclerck

**Comment by joren** [comment]
@reinoutdeclerck the link does work ATM, could you change the link or have a look what's wrong?
screen shot 2018-03-26 at 14 35 47

**Comment by reinoutdeclerck** [comment]
Strange… I revised by changing to an email address (see the new merge request).

**Pull request merged**
